name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello Github Actions"
      - name: Print Good bye
        run: echo "Done - bye!"
      - name: Print multiple lines
        run: |
          echo "first Line"
          echo "Second Line"
